2025-10-17 05:01:24,184 [processing](INFO): Initializing backseat process (pilot lrauv based on marl)
2025-10-17 05:01:28,800 [Logger](CRITICAL): Uncaught exception
Traceback (most recent call last):
  File "./backseat_app/main.py", line 111, in <module>
    main()
  File "./backseat_app/main.py", line 107, in main
    backseat_app.spin()
  File "./backseat_app/main.py", line 75, in spin
    self.marl_processor.compute_new_heading()
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/processing.py", line 192, in compute_new_heading
    self.new_action = self.rl_tracking.newAction(self.target_address,agents_range,agents_pose,agents_depth,agents_timestamp,new_range=False)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/utils.py", line 885, in newAction
    tuple = utm.from_latlon(lrauvLatLon[0], lrauvLatLon[1])
TypeError: 'int' object is not subscriptable
