2025-10-17 06:00:48,177 [processing](INFO): Initializing backseat process (pilot lrauv based on marl)
2025-10-17 06:00:51,804 [Logger](CRITICAL): Uncaught exception
Traceback (most recent call last):
  File "./backseat_app/main.py", line 111, in <module>
    main()
  File "./backseat_app/main.py", line 107, in main
    backseat_app.spin()
  File "./backseat_app/main.py", line 75, in spin
    self.marl_processor.compute_new_heading()
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/processing.py", line 191, in compute_new_heading
    self.new_action = self.rl_tracking.newAction(self.target_address,agents_range,agents_pose,agents_depth,agents_timestamp,new_range=False)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/utils.py", line 908, in newAction
    tuple = utm.from_latlon(agents_lrauvLatLon[i][0], agents_lrauvLatLon[i][1])
  File "/home/maiv/.local/lib/python3.8/site-packages/utm/conversion.py", line 232, in from_latlon
    raise OutOfRangeError('latitude out of range (must be between 80 deg S and 84 deg N)')
utm.error.OutOfRangeError: latitude out of range (must be between 80 deg S and 84 deg N)
