2025-10-13 15:45:53,049 [processing](INFO): Initializing backseat process (pilot lrauv based on marl)
2025-10-13 15:45:55,846 [Logger](CRITICAL): Uncaught exception
Traceback (most recent call last):
  File "./backseat_app/main.py", line 111, in <module>
    main()
  File "./backseat_app/main.py", line 107, in main
    backseat_app.spin()
  File "./backseat_app/main.py", line 75, in spin
    self.marl_processor.compute_new_heading()
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/processing.py", line 135, in compute_new_heading
    new_heading = self.rl_tracking.newAction(self.target_address,self.target_range,self.lrauv_pose,self.lrauv_depth,self.target_timestamp)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/utils.py", line 863, in newAction
    self.locpfls.updatePF(dt=elapsed_time, new_range=new_range, z=planarRange, myobserver=self.lrauv_position, update=new_range)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/utils.py", line 532, in updatePF
    self.pf.init_particles(position=self.pf.previous_observer, slantrange=self.pf.previous_z)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/utils.py", line 138, in init_particles
    self.x[i][0] = r*np.cos(t)+position[0]
IndexError: list index out of range
