2025-10-01 17:24:16,283 [AppConfig](INFO): Reading configuration file: /home/maiv/.local/lib/python3.8/site-packages/backseat_app/config/app_cfg.yml
2025-10-01 17:24:16,284 [Logger](CRITICAL): Uncaught exception
Traceback (most recent call last):
  File "backseat_app/main.py", line 98, in <module>
    main()
  File "backseat_app/main.py", line 87, in main
    cfg = read_config(args.config)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/config/AppConfig.py", line 49, in read_config
    cfg = yaml.safe_load(f)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/home/maiv/.local/lib/python3.8/site-packages/backseat_app/config/app_cfg.yml", line 7, column 1
expected <block end>, but found '<block sequence start>'
  in "/home/maiv/.local/lib/python3.8/site-packages/backseat_app/config/app_cfg.yml", line 21, column 7
